### ISSUE TITLE
package(npm-registry): publish `1.3.0`

### ISSUE THREAD

**Issue by GervinFung** [kalmecak/moment-business-days#107]
Bonjour, have you forgotten to publish latest version on NPM registry? The latest version was 3 years ago - `1.2.0`, it will be really helpful if u guys can publish it, as of right now I am installing this repo of latest commit

**Comment by mcdado** [comment]
Hello, unfortunately @kalmecak is not responding and he's the only one with access to npm. A workaround is this: https://github.com/kalmecak/moment-business-days/issues/99#issuecomment-1193075966

**Comment by GervinFung** [comment]
I see, that's what I did but with a specific git commit hash appended at the end of the url, thanks for your quick feedback!
