### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by moxious** [kalmecak/moment-business-days#11]
```
✗ Low severity vulnerability found on moment@2.10.6
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:moment:20160126
```

It appears there is still this vulnerability in the latest published version 0.0.10 available from npmjs.

Looks also like there's already been a PR merged to address this, but would you consider issuing a new release to address this?

**Comment by kalmecak** [comment]
Sorry for the delay, now is solved.
