### ISSUE TITLE
businessDiff does not consider holidays

### ISSUE THREAD

**Issue by mnapoli76** [kalmecak/moment-business-days#13]
Hello everyone, I tried to use the businessDiff function but it seems that it's not considering holidays that have been specified in the locale... has anyone faced the same issue?

**Comment by jarednova** [comment]
@mnapoli76 me too! I copied-and-pasted the example exactly but no dice; same result as the normal `businessDiff` calculation

**Comment by jarednova** [comment]
@mnapoli76 after digging in some more, there's nothing in the `businessDiff` method that considers holidays. I'm working on a PR right now to (hopefully) solve that

**Comment by kpihus** [comment]
My last PR fixed that thing. Merged by now.

**Comment by kalmecak** [comment]
Sorry for the delay, it is solved in the new version, update the package please.
