### ISSUE TITLE
Dynamic holidays?

### ISSUE THREAD

**Issue by moxious** [kalmecak/moment-business-days#14]
The documentation clearly states how to set holidays in the locale, but these are particular days of particular years.  Is there a recommended way to specify holidays dynamically by a function?   This would permit saying things for example like "Thanksgiving is the Second Thursday in November".   It's not going to work to specify the individual day for every year, past and future.

**Comment by moxious** [comment]
Am I correct in assuming that this code here: https://github.com/kalmecak/moment-business-days/blob/master/index.js#L8  means that this is not possible?

**Comment by kalmecak** [comment]
I'll be working on it, if you want to contribute your PR will be welcome!

**Comment by fishcharlie** [comment]
@kalmecak Any updates on this?

**Comment by mcdado** [comment]
@fishcharlie it should be implemented… check the test called "Moment Business Days" > ".isBusinessDay" > "When today is a holiday determined by a function".

If you consider it solved, can you let me know so I close this issue? Thanks!

**Comment by sgarcia30** [comment]
Was this resolved?  If so, what's the solution?  I tried reading through the `index.js` file to see if I could see code that might account for a dynamic holiday, but I don't see it.

**Comment by nawressissa** [comment]
Hello ,any updates on this, i need to add two format holiday
 momentbusiness.updateLocale('fr', {
            holidays: ['01-01', '05-01', '05-08', '05-30', '07-14', '08-15',
             '11-01', '11-11', '12-25', '04-22-2019' , '06-10-2019'],
            holidayFormat: 'MM-DD-YYYY', 'MM-DD'
        });

**Comment by mcdado** [comment]
@sgarcia30 @nawressissa It is not exactly documented, but when you update your locale like [shown on the README](https://github.com/kalmecak/moment-business-days#use-localization-to-configure-holidays), you can specify a `holiday` property which is a function that returns a boolean, returning true makes it an holiday:

```js
var moment = require('moment-business-days');

var july4th = '07-04-2015';
var laborDay = '09-07-2015';

moment.updateLocale('us', {
    holidays: [july4th, laborDay],
    holidayFormat: 'MM-DD-YYYY',
    holiday: function (thisMoment) {
        // Months indexed starting at 0, so December is 11.
        // Every Christmas is a holiday, no matter the year
        return thisMoment.month() === 11 && thisMoment.date() === 25;
     }
});
```

I am aware that this means coding all dynamic holidays, which is a bit tedious and not really declarative. The closest approximation would be more like the following:

```js
holiday: function (m) {
    if (m.month() === 11 && m.date() === 25) return true; // christmas
    if (m.month() === 6 && m.date() === 4) return true; // july 4th
    return false
}
```

The code that make this work is here: https://github.com/kalmecak/moment-business-days/blob/6d2f1f502f4528912fd09caf895dc5f2a22588af/index.js#L15-L20

See also the existing test here: https://github.com/kalmecak/moment-business-days/blob/6d2f1f502f4528912fd09caf895dc5f2a22588af/tests/test.js#L43-L70

Sorry for taking some time to respond, I hope this helps!
