### ISSUE TITLE
Client-side version for cdnjs?

### ISSUE THREAD

**Issue by hare1039** [kalmecak/moment-business-days#23]
Hi,
I'm a member from cdnjs, and we receive a request to add this library.
https://github.com/cdnjs/cdnjs/issues/10228

As we can only host client-side libraries, will this library plan to release one in the future?

Thanks!

**Comment by kalmecak** [comment]
Hi, sorry for the delay, I have been so busy on work, yes, I'll work for support client side.

**Comment by IvanRibakov** [comment]
Any news on the client-side support?

**Comment by IvanRibakov** [comment]
Code from this PR (https://github.com/kalmecak/moment-business-days/pull/7/files) does the job, though it doesn't seem to be present in the latest version. Had to manually modify source code...

**Comment by fishcharlie** [comment]
@kalmecak Any updates on this?

**Comment by mcdado** [comment]
What would make this library compatible with the browser? I'm asking because I've only used it in Node.

The PR that @IvanRibakov mentions is now merged and improved upon with Webpack compatibility added in 1.0.4. Does it mean that we're already good, @hare1039 ?

**Comment by hare1039** [comment]
@mcdado Thanks for telling me.
