### ISSUE TITLE
businessDiff only returning absolute value

### ISSUE THREAD

**Issue by thorakmedichi** [kalmecak/moment-business-days#32]
At the moment businessDiff only returns the absolute value rather than a relative value. This is an issue because if I am trying to use this in an if clause I am getting incorrect values.

if (startDate.businessDiff(moment()) <=3)  returns false if today is July 30 and the date I am comparing it too is June 15 because the value businessDiff gives is a positive number not a negative one.

**Comment by oleg-koval** [comment]
@thorakmedichi Hi, are you still interested in this feature?

**Comment by lyleunderwood** [comment]
Just got caught out by this.

`businessDiff` should mirror the functionality of moment's `diff` which is [to return a negative number](https://momentjs.com/docs/#/displaying/difference/):

>If the moment is earlier than the moment you are passing to moment.fn.diff, the return value will be negative.

**Comment by lyleunderwood** [comment]
You can try my fix for this by changing your `moment-business-days` dep in your `package.json` to look like this:

```json
"moment-business-days": "lyleunderwood/moment-business-days#negative-diff",
```

and then running `npm i` or `yarn` again.

**Comment by tommyalvarez** [comment]
+1 to This. @kalmecak can you implement the fix to mirror what moment does?

**Comment by mcdado** [comment]
Shall we bump the minor version or jump to next major?

**Comment by tommyalvarez** [comment]
@lyleunderwood If i use your repo my npm install in production server hangs like 200 seconds in `loadIdealTree:loadAllDepsIntoIdealTree: sill install loa`

Do you know what could that be?

**Comment by lyleunderwood** [comment]
@tommyalvarez Not really, but [this issue looks relevant](https://github.com/npm/npm/issues/17228).

I'm gonna update my PR to try and get this into a version.

**Comment by mcdado** [comment]
@tommyalvarez that belongs to a different issue, anyway I'll change the repo url from ssh to https

**Comment by thorakmedichi** [comment]
> @thorakmedichi Hi, are you still interested in this feature?
> because I found its useful as well, f.e. [Luxon](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-diff) has this on `.diff` and `.diffNow`

I found a work around and the project I was working is now shipped. So at this time I am fine.

**Comment by robclancy** [comment]
I love running into an issue and then finding is was reported  2 years earlier, with a PR from half a year earlier that fixes the issue all open and ignored by the person who maintained the package.

Has anyone forked this project? there was a release after this PR was submitted and the package so indicates the package owner is only interested in changing/fixing things that effect him directly.

**Comment by mcdado** [comment]
While I'm not the package owner, I always contributed to this package because forking the project on such a niche functionality gives no upside to anybody. That being said it it true that this feature was ready for merging, I'll bump it to @kalmecak
