### ISSUE TITLE
businessDiff returns 1 when two dates are on the same day but few hours apart

### ISSUE THREAD

**Issue by samsonkeung** [kalmecak/moment-business-days#34]
```
it("should return 0 if two dates are the on the same day but different time", () => {
            const earlierDate = moment("2017-08-04T01:00:00.000Z");
            const laterDate = moment("2017-08-04T02:00:00.000Z");
            // The two dates above are only an hour apart.
            const diff = earlierDate.businessDiff(laterDate);

            assert.equal(diff, 0); // Fail because actual result is 1
        });
```

The behaviour should be consistent with the ```diff``` function in Moment.js where they return 0 as the result of ```earlierDate.diff(laterDate, "days")```

**Comment by bfintal** [comment]
Encountered this too.

**Comment by calin1611** [comment]
I can confirm this. I ran into the same issue and used the approach suggested by @bfintal

**Comment by oleg-koval** [comment]
have the same, will use the approach suggested by @bfintal

**Comment by komarovalexander** [comment]
> Encountered this too. If the moment has hours, and both dates are in a weekday, the calculation has an extra day.
> 
> It works fine if the moment doesn't have hours in it.
> 
> Workaround:
> 
> ```
> const diffBusinessDays = ( moment1, moment2 ) => {
>     const m1 = moment( moment1.format( 'DD/MM/YYYY' ), 'DD/MM/YYYY' );
>     const m2 = moment( moment2.format( 'DD/MM/YYYY' ), 'DD/MM/YYYY' );
>     return m1.businessDiff( m2 );
> }
> ```

Thanks for the solution but I think it is better to do it with startOf
 ```
const diffBusinessDays = ( moment1, moment2 ) => {
    const m1 = moment1.startOf('day');
    const m2 = moment2.startOf('day');;
    return m1.businessDiff( m2 );
 }
```
