### ISSUE TITLE
Inconsistency between add and subtract on Sunday

### ISSUE THREAD

**Issue by eyalhakim** [kalmecak/moment-business-days#35]
Adding 2 business days from November 5th (Sunday) returns November 7th (Tuesday).
Subtracting 2 business days from November 7th (Tuesday) returns November 3rd (Friday)

**Comment by mcdado** [comment]
That seems right to me. If you add one business day from a non business day, it shouldn’t skip two days. And the logic for subtracting seems right to me.

Take in consideration time along with date. You might want to use `.startOf(‘day’)`
