### ISSUE TITLE
Am I using .businessAdd() wrong? or is this 

### ISSUE THREAD

**Issue by paul42** [kalmecak/moment-business-days#4]
I was attempting to use your super handy library - but I think something went awry or I'm using it wrong - 

here is what I have: https://gist.github.com/paul42/6f722a1523d0d5fec119
> 'use strict';
> 
> var moment = require('moment-business-days');
> var holidayArray = [
>   '01-01-2016',
>   '01-02-2016',
>   '01-03-2016',
>   '02-07-2016',
>   '02-08-2016',
>   '02-09-2016',
>   '02-10-2016',
>   '02-11-2016',
>   '02-12-2016',
>   '02-13-2016',
>   '02-22-2016',
>   '03-08-2016'
> ]
> 
> var holidayFormat = 'MM-DD-YYYY';
> moment.locale('cn', {
>   holidays: holidayArray,
>   holidayFormat: holidayFormat
> });
> 
> function projectSLA(date, stringformat, businessDaysToAdd){
>   return moment(date, stringformat).businessAdd(businessDaysToAdd)._d;
> }
> 
> console.log('02-08-2016 + 1 = '+projectSLA('02-08-2016', holidayFormat, 1))
> console.log('02-08-2016 + 2 = '+projectSLA('02-08-2016', holidayFormat, 2))
> console.log('02-08-2016 + 3 = '+projectSLA('02-08-2016', holidayFormat, 3))
> console.log('02-08-2016 + 4 = '+projectSLA('02-08-2016', holidayFormat, 4))
> console.log('02-08-2016 + 5 = '+projectSLA('02-08-2016', holidayFormat, 5))
> console.log('02-08-2016 + 6 = '+projectSLA('02-08-2016', holidayFormat, 6))
> console.log('02-08-2016 + 7 = '+projectSLA('02-08-2016', holidayFormat, 7))
> console.log('02-08-2016 + 8 = '+projectSLA('02-08-2016', holidayFormat, 8))
> console.log('02-08-2016 + 9 = '+projectSLA('02-08-2016', holidayFormat, 9))

and I'd expect the output to increment the day, but it takes a step back actually:

output: https://gist.github.com/paul42/d87a11bc2db754326929
output (pasted):
> $ node index.js 
> 02-08-2016 + 1 = Mon Feb 15 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 2 = Tue Feb 16 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 3 = Wed Feb 17 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 4 = Thu Feb 18 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 5 = Mon Feb 15 2016 00:00:00 GMT-0700 (MST) << This should have been Feb 19th.
> 02-08-2016 + 6 = Tue Feb 16 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 7 = Wed Feb 17 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 8 = Thu Feb 18 2016 00:00:00 GMT-0700 (MST)
> 02-08-2016 + 9 = Fri Feb 19 2016 00:00:00 GMT-0700 (MST)

Am I calling this wrong, or is the problem due to how I have my holidays set up? Is it because i input chinese new year, which runs a whole week, so performing .buisnessAdd(5) causes issues because it finds the first 'non-holiday' as the 13th, and then steps forward?

**Comment by paul42** [comment]
I think the root of the issue is that inside .businessAdd, https://github.com/kalmecak/moment-business-days/blob/master/index.js#L63
this line:
> var d = this.clone().add(Math.floor(days / 5) * 7 * signal, 'd'); 
increases the day, but does not check if advancing by a week counts holidays or not. 
I'm going to start tinkering with a pull request, but let me know if I'm on the right path.

Thanks in advance,
Paul

**Comment by kalmecak** [comment]
Hi Pau! I've been very bussy at work, please feel free to make pull requests and thanks for contributing

**Comment by paul42** [comment]
Hi @kalmecak, 
I took a stab at it, I believe I have it working properly, but if you have a moment to take a look, I'd appreciate it!

Thanks in advance,
Paul
