### ISSUE TITLE
Help: Include Sunday in Business Day

### ISSUE THREAD

**Issue by yunus89** [kalmecak/moment-business-days#42]
When using 
`moment.locale('us', {
   workingWeekdays: [1,2,3,4,5,6,7] 
});`

and check `moment('01-07-2018', 'MM-DD-YYYY').isBusinessDay()` always returns false yet is a working day in the configuration above.

Note: '01-07-2018' is a Sunday

How can one make `Sunday` a working day?

**Comment by mcdado** [comment]
Sunday is 0.

```
moment.locale('us', { workingWeekdays: [0,1,2,3,4,5,6] }); // Sunday, Monday, …, Saturday
```

**Comment by yunus89** [comment]
Oh, thanks, it now working as expected.
