### ISSUE TITLE
Attempts to manipulate invalid moment objects result in infinite loops

### ISSUE THREAD

**Issue by nfavaro** [kalmecak/moment-business-days#43]
Attempts to manipulate invalid moment objects using `businessAdd()` result in infinite loops because invalid moment objects [behave like NaN in floating point operations](https://momentjs.com/docs/#/parsing/is-valid/). 

Since moment still allows addition to an invalid moment object (resulting in a still invalid moment object), the condition `day.isBusinessDay()` never evaluates to true, thus `remaining` is never decremented, and the `while` loop never exits:

https://github.com/kalmecak/moment-business-days/blob/88ab6e5656734aa43f6d604afea10f7023cd2134/index.js#L72-L87

### Steps to reproduce
```js
const moment = require('moment-business-days')

const invalidMoment = moment(null)

invalidMoment.isValid() // returns false

invalidMoment.businessAdd(3) // observe infinite loop
```

Similar issues arise with `monthBusinessDays()`, `monthNaturalDays()`, `monthBusinessWeeks()`, and `monthNaturalWeeks()`

This can pretty easily be prevented by adding a validity check, e.g.:
```js
moment.fn.businessAdd = function(number, period) {
    if (!this.isValid()) {
        return this; // or null, or a sentinel value
    }
    ....
```

I'm happy to follow up with a pull request if needed.

**Comment by kalmecak** [comment]
Thanks nfavaro, would be great if you can help me with a pull request.
