### ISSUE TITLE
businessDiff should not take into account time of day

### ISSUE THREAD

**Issue by jolim24601** [kalmecak/moment-business-days#52]
Can this be fixed?

**Comment by jolim24601** [comment]
Example:

![image](https://user-images.githubusercontent.com/12823853/45048192-40bc8d00-b049-11e8-9e6e-5f89c0f02ff1.png)

**Comment by jolim24601** [comment]
Sorry the real issue here is that the behavior of `businessDiff` is not the same as `diff` in `moment` which does not add an extra day based on `time`. I think the more consistent behavior here would be to check only for the date and ignore the time.

**Comment by mcdado** [comment]
See https://github.com/kalmecak/moment-business-days/pull/16

**Comment by jolim24601** [comment]
Thanks @mcdado, I changed the title to reflect the actual issue that I'm seeing.

**Comment by mcdado** [comment]
> I think the more consistent behavior here would be to check only for the date and ignore the time.

Is it feasible for you to use `.startOf('day')` to reset moments to midnight and avoid the issue? Or you actually need to keep track of the time?

**Comment by mcdado** [comment]
Maybe a parameter could be added to diff, just like Moment. See [moment.diff()](https://github.com/moment/moment/blob/2e2a5b35439665d4b0200143d808a7c26d6cd30f/src/lib/moment/diff.js
)

**Comment by Asalem1** [comment]
@mcdado is there any progress on this? The logic is currently incrementing for each day regardless of when a day has passed (similar to the `startOf('day')` example you listed above), but this is inconsistent with the functionality of `moment.diff`. 

For example, using `moment.diff()` when two days are 23 hours apart will register as `0` on `moment.diff()`. However, using `businessDiff()` with the same parameters will register a difference of `1`.

**Comment by zelongc** [comment]
I found the similar problem in `businessAdd` function, and I resolved this **taking current day into consideration** problem by removing time before the date using `businessAdd`,

```
moment(new Date(), 'DD-MM-YY').businessAdd(X);
```

hope this may help those who met the same problem.

**Comment by mcdado** [comment]
> I found the similar problem in `businessAdd` function, and I resolved this **taking current day into consideration** problem by removing time before the date using `businessAdd`,
> 
> ```
> moment(new Date(), 'DD-MM-YY').businessAdd(X);
> ```
> 
> hope this may help those who met the same problem.

Thanks @zelongc, it's the same logic of adding `.startOf('day')` before `.businessAdd()`. Indeed I hope it helps onlookers.
