### ISSUE TITLE
Fractional day causes infinite loop in businessAdd

### ISSUE THREAD

**Issue by avenue19** [kalmecak/moment-business-days#55]
Run test that calls businessAdd with a fractional number of days:

      it('adds business days only, excluding weekends, handles fractional days without infinite loop ', function (done) {
        var newBusinessDay = moment('11-03-2015 12:42:00', 'MM-DD-YYYY hh-mm-ss').businessAdd(10.5);
        expect(newBusinessDay.format('D')).to.eql('17');
        done();
      });
$ npm test

> moment-business-days@1.0.6 test XXXXXX\moment-business-days
> mocha tests/*

   Moment Business Days
    .prevBusinessDay
      When today is Monday
        √ should be Friday
    .isBusinessDay
      When today is a regular weekday
        √ should be true
      When today is a weekend
        √ should be false
      When today is a holiday determined by a function
        √ should be false
      When today is custom working day
        √ Should be true
      When today is a holiday
        √ should be false
    .businessDaysIntoMonth
      When moment object is invalid
        √ should return NaN
      On Wednesday, September 23rd 2015
        √ should be 17 when there are no holidays
        √ should be 16 when considering labor day
    .businessAdd
      When moment object is invalid
        √ should return a new invalid moment object
      On Tuesday, November 3rd 2015
        √ adds business days only, excluding weekends, even over 2 weeks
        √ adds business days only, excluding weekends

(test hangs here)

Cause: once the remaining variable goes negative, due to the fractional day, the while loop never terminates. It needs to test if remaining is > 0.

I'm not sure if you want to support this use case, throw an error, or silently ignore the fraction. I have a pull request ready if you want the latter.

**Comment by kalmecak** [comment]
Can you help us sending a Pull Request fixing this issue?

**Comment by avenue19** [comment]
I sent a pull request...hope I did it right ;)
