### ISSUE TITLE
Please include index.d.ts in npm package

### ISSUE THREAD

**Issue by queejie** [kalmecak/moment-business-days#56]
Thanks very much for this library!  Could you please update the npm package to include the index.d.ts file?  Each of us on our dev team can put it in manually, we have to remember to do it every time we update our npm modules. (We're using it with Angular/Typescript.)

**Comment by mcdado** [comment]
Hi, thank you for your feedback! 😉

I hope that @kalmecak can push it out soon, it was enough of a big deal for me to look into declaration files and make a PR.

**Comment by kalmecak** [comment]
Hi guys, actually I'm so busy in my job, can you help me with a pull request to integrate it to this library?
Thanks!

**Comment by mcdado** [comment]
> Hi guys, actually I'm so busy in my job, can you help me with a pull request to integrate it to this library?
> Thanks!

It's already merged… it just needs to be published to npm.
I can help with that if you grant me access to the package

**Comment by kalmecak** [comment]
Thanks a lot guys, I just published a new version in npm (1.1.0) please let me know if it is ok

**Comment by mcdado** [comment]
Actually testing out the new version I realized there were some problems with the previous declaration file, so I updated it. If you require `moment-business-days` **instead of** `moment`, the typings don't get picked up.

@queejie would you mind trying this and see if you have any problems? https://github.com/kalmecak/moment-business-days/pull/57

@kalmecak I'm sorry about this, if it's all good would it be okay to make another release? In this case it would be a [PATCH SemVer](https://semver.org/).

**Comment by kalmecak** [comment]
Thanks, the version 1.1.1 is now available on npm. Let me know if it's ok.

**Comment by mcdado** [comment]
Thank you so much @kalmecak! It's working great now!

<img width="609" alt="screenshot 2018-11-13 at 19 52 09" src="https://user-images.githubusercontent.com/898057/48435870-b77ab280-e77d-11e8-9bc8-707c5ea4c564.png">

<img width="277" alt="screenshot 2018-11-13 at 20 01 47" src="https://user-images.githubusercontent.com/898057/48436453-f9582880-e77e-11e8-9358-2f696f8d728a.png">

<img width="555" alt="screenshot 2018-11-13 at 20 01 34" src="https://user-images.githubusercontent.com/898057/48436463-007f3680-e77f-11e8-864b-0f1ad8832d46.png">

**Comment by queejie** [comment]
Sorry I didn't respond sooner, but I was away.  I didn't have any problems with the declarations.  Maybe because I'm using import in Angular?

**Comment by mcdado** [comment]
Well, before there were no problems if you imported `moment` and `moment-business-days` separately. But if as suggested in the project README you import only `moment-business-days` instead of `moment`, then the declarations wouldn't work. Now it's all good though!
