### ISSUE TITLE
workingWeekdays doesn't appears and Deprecation warning

### ISSUE THREAD

**Issue by LeonardoVini** [kalmecak/moment-business-days#58]
I'm trying to configure workingWeekdays but it doesn't appear for me to do that.

![image](https://user-images.githubusercontent.com/37921663/49023532-8dae8c00-f17e-11e8-85af-2e3ff70813bd.png)

![image](https://user-images.githubusercontent.com/37921663/49023827-378e1880-f17f-11e8-974f-2a42b1e1a61d.png)

And I'm receiving a deprecation warning:
"Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non-RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release"

```
import { Injectable } from '@angular/core';
import * as moment from 'moment-business-days';

@Injectable({
    providedIn: 'root'
})

export class WorkingDays {

    public moment = moment

    public natal = "12-25-2018"
    public sextaFeiraSanta = "04-19-2019"
    public tiradentes = "04-21-2019"
    public pascoa = "04-21-2019"
    public diaTrabalhador = "05-01-2019"
    public corpusChristi = "06-20-2019"
    public indepedenciaBrasil = "09-07-2019"
    public nossaSenhoraAparecida = "10-12-2019"
    public finados = "11-02-2019"
    public proclamacaoRepublica = "11-15-2019"
    public natal2019 = "12-25-2019"

    public diff: number

    TestDays() {

        this.moment.updateLocale('pt-br', {
            holidays: [
                this.natal,
                this.sextaFeiraSanta,
                this.tiradentes,
                this.pascoa,
                this.diaTrabalhador,
                this.corpusChristi,
                this.indepedenciaBrasil,
                this.nossaSenhoraAparecida,
                this.finados,
                this.proclamacaoRepublica,
                this.natal2019,
                '11-27-2018'
            ],
            holidayFormat: 'MM-DD-YYYY',
            
        })

        var start = moment('11-26-2018')
        var end = moment('11-30-2018')

        this.diff = start.businessDiff(end)

        console.log(this.diff)
    }

}
```
I'm using Angular 6.

How I resolve this issues?

**Comment by kalmecak** [comment]
Hi Leonardo!

This warning is fired by moment JS core because the standar format is *YYYY-MM-DD*, [that is in their docs](https://momentjs.com/docs/#/parsing/string/)

So you can indicate moment the format you are using:

```javascript
var start = moment('11-26-2018', 'MM-DD-YYYY');
var end = moment('11-30-2018', 'MM-DD-YYYY');

**Comment by LeonardoVini** [comment]
Hi, kalmecak!

Thank for your answer but why workingWeekdays doesn't appear to me?

**Comment by mcdado** [comment]
@LeonardoVini I fixed it in https://github.com/kalmecak/moment-business-days/commit/025c102b5a127f21578de6a93ba26d36dde91b88
It didn't show up in IntelliSense but it would work if you used it in your code.

@kalmecak it's a trivial change but it can be published. I had already improved the definitions file in other ways since last npm publish. If you need any help with publishing you can give me publish rights to the npm module if you want.

**Comment by LeonardoVini** [comment]
Thank you men

**Comment by mcdado** [comment]
> @mcdado Gracias por tu contribuciones!! estoy revisando la docu para agregarte en NPM con los permisos para que apoyes al proyecto al hacer los releases cuando se me dificulte. Si ya tienes la documentación para hacerlo, me la pasas para hacer el add por fa??? Saludos!

I checked [npm's docs page](https://docs.npmjs.com/adding-collaborators-to-private-packages-owned-by-a-user-account) and we would both need to have paid accounts. In that case it's okay, you can keep publishing on your own 😄
