### ISSUE TITLE
Running in Browser

### ISSUE THREAD

**Issue by LeandroFavero** [kalmecak/moment-business-days#6]
Hi,

Your module is great! But could be run in browser. Well, I changed the source, including this in first line:

if (typeof window === 'undefined') {
    var moment = require('moment'); //http://momentjs.com/
}

So now, moment-business-days runs in NodeJS and Browser. What you think?

**Comment by kalmecak** [comment]
That's great! thanks for contributing, please make a pull request, I'll merge it on master

**Comment by LeandroFavero** [comment]
Done!
