### ISSUE TITLE
Creating a v1.2.0 release

### ISSUE THREAD

**Issue by PeterKruzlics** [kalmecak/moment-business-days#70]
Hello, I see there's a v1.2.0 commit, would we be able to get a new release published to npm? Thanks!

**Comment by mcdado** [comment]
@kalmecak I already drafted the release on GitHub, if you don't mind could you save it and then publish to npm as well? Thanks

**Comment by Lobato-Orange** [comment]
Yes please.... Do this.

**Comment by dguo** [comment]
I think this issue can be closed. I see v1.2.0 on npm (published on April 16, 2020).
