### ISSUE TITLE
Security issue in moment version

### ISSUE THREAD

**Issue by ianaya89** [kalmecak/moment-business-days#8]
Hey, a [security issue](https://nodesecurity.io/advisories/55) (**Regular Expression Denial of Service**) was discovered in the version of moment that you are using (2.10.X).

This issue was already solved in [v2.11.2](https://github.com/moment/moment/issues/2947).

Did you consider to make the upgrade?

Thanks!

**Comment by kalmecak** [comment]
Thanks, now updated.
